### ISSUE TITLE
AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED ???

### ISSUE THREAD

**Issue by Michael1969** [googleads/google-api-ads-ruby#104]
Hi,

https://github.com/googleads/google-api-ads-ruby/wiki/API-access-using-own-credentials-(installed-application-flow)

i did this, setup_oauth2.rb in console, got token and access token.
` adwords = AdwordsApi::Api.new
    campaign_srv = adwords.service(:CampaignService, :v201607)
    campaign_srv.get({:fields => ['1634567','campaing name', 'Paused']})`

result: AdwordsApi::V201607::CampaignService::ApiException: [AuthenticationError.CLIENT_CUSTOMER_ID_IS_REQUIRED @ ; trigger:'<null>']

why I need CLIENT_CUSTOMER_ID? 

thanks, Michael

**Comment by mcloonan** [comment]
You need to specify the client customer ID (It's the account ID in the format XXX-XXX-XXXX on the user interface) so that the API knows which account you're trying to access. You can specify it in the adwords_api.yml file or in the hash when you instantiate the API object. You can either specify it with or without the dashes. See: https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/adwords_api.yml#L36

If you're only working on a single account, it may seem redundant that you need to specify your account ID if you generated your refresh token from a specific account. However, consider the case where you generate your refresh/access token as a manager account, which has access to multiple child accounts, and you want to write an application that has access to all of them. You can see how the actual account ID for which you want data becomes important.

**Comment by Michael1969** [comment]
thank you, mclooan.
client_customer_id was missing. 

I have to wait for production dev token from google, takes 14 days.

`AdwordsApi::V201607::CampaignService::ApiException: [QuotaCheckError.DEVELOPER_TOKEN_NOT_APPROVED @ ; trigger:'<null>']`

**Comment by dklimkin** [comment]
While waiting, you can use API against a test account for development. See:

  https://developers.google.com/adwords/api/docs/guides/accounts-overview#test_accounts
