### ISSUE TITLE
Can't specify ad unit id on creation

### ISSUE THREAD

**Issue by ericescalante** [googleads/google-api-ads-ruby#108]
Hi, thanks for this SDK, it's extremely useful. One thing that's causing us issues is that we need to specify the unit id (so we can use it programatically somewhere else). Even though we specify it, units get created with a numeric sequence.

```
{ :id => "xxx_#{domain}_#{unit_type}",
  :name => "xxx_#{domain}_#{unit_type}",
  :parent_id => effective_root_ad_unit_id,
  :target_window => 'BLANK',
  :ad_unit_sizes => [creative_placeholder] 
}
```

Results in:

```
Ad unit with ID: 162597490, name: xxx_yyy_zzz and status: ACTIVE was created.
```

Is there a flag I'm missing in order to override the sequence or is this something that can be fixed? Thanks :)

**Comment by christopherseeley** [comment]
The ID the unique ID for DFP that is assigned by Google. You're probably looking for the [adUnitCode](https://developers.google.com/doubleclick-publishers/docs/reference/v201608/InventoryService.AdUnit#adUnitCode).

In the future, for questions about the DFP API (rather than the ruby client library itself) please use our [developer forums](https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api). Thanks!

**Comment by ericescalante** [comment]
Thanks @christopherseeley! Will do :)
