### ISSUE TITLE
[DFP] How to get already generated reports?

### ISSUE THREAD

**Issue by evg2108** [googleads/google-api-ads-ruby#121]
I created Report Query in UI, which generate reports every day for previous day. So I have a several reports. How can I get these reports using this gem? In manuals I found only how to get report queries, create report job and download report using report job id. Is there any way how to search reports using name and creation date (for example with a PQL statements), and download them?

**Comment by mcloonan** [comment]
Hello,

For product level questions like "How do I use the API do do [some task]?", you should be asking on the forum rather than here. This issue tracker is for bug reports with the library itself.

You can find the DFP forum here: https://groups.google.com/forum/#!forum/google-doubleclick-for-publishers-api
