### ISSUE TITLE
how can I a Creative's Native Style?

### ISSUE THREAD

**Issue by pacuna** [googleads/google-api-ads-ruby#122]
Right now I have a Creative object with the following attributes:

```
=> [:advertiser_id, :id, :name, :size, :preview_url, :last_modified_date_time, :creative_template_id, :is_interstitial, :is_native_eligible, :is_safe_frame_compatible, :destination_url, :creative_template_variable_values, :ssl_scan_result, :ssl_manual_override, :locked_orientation, :xsi_type] 
```

Using the `creative_template_id` I can get the CreativeTemplate object, with the following attributes:

```
=> [:id, :name, :description, :variables, :snippet, :status, :type, :is_interstitial, :is_native_eligible, :is_safe_frame_compatible]
```

Now, what I need is the html and css snippet from the Native Style associated to that creative. Using the API I don't know how to do it since several Native Styles can have the same creative_template_id so if I query the NativeStyleService filtering by creative_template_id, I get more than one result.
Using the DFP interface I know which is the Native Style I need. If using the API I get that object, it has the following attributes:

```
 => [:id, :name, :html_snippet, :css_snippet, :creative_template_id, :is_fluid, :targeting, :size] 
```

Which are the ones I need. But how can I get those by knowing the Creative Id I'm looking for?

Thanks.

**Comment by christopherseeley** [comment]
This help center article might help:
https://support.google.com/dfp_premium/answer/6366905#add-native-styles

The native style that is used is determined by the targeting. You can get the targeting from the line item the creative is associated with.

Since this is a product question and not specific to the Ruby library, you can ask on the DFP product forum if you need more information:
https://productforums.google.com/forum/#!forum/dfp
