### ISSUE TITLE
Create user using adwords api

### ISSUE THREAD

**Issue by nitanshu** [googleads/google-api-ads-ruby#134]
Is Google adwords supports adding user into it. If yes then how would I do that using this gem.

**Comment by dklimkin** [comment]
Hello nitanshu,

Please note this is not a library specific question or issue. Please refer to the product specific support forum instead of logging and issue going forward:

  https://groups.google.com/forum/#!forum/adwords-api

As per the question, no, AdWords API does not allow user management. It can be used to manage account entities only, all user permissions should be set via the AdWords user interface.
