### ISSUE TITLE
Bug for report service download_report.rb example for DFP_API

### ISSUE THREAD

**Issue by hamdibayhan** [googleads/google-api-ads-ruby#142]
I am trying download_report.rb with 'CSV_DUMP' export_format to download the report, but the contents of the downloaded file looks like the image below. Is it a bug?

![screen shot 2017-12-21 at 15 20 43](https://user-images.githubusercontent.com/10344177/34256083-a5ad8e76-e664-11e7-9b27-51c3e145bf2c.png)

**Comment by mcloonan** [comment]
CSV_DUMP is not a supported download format. See: https://developers.google.com/adwords/api/docs/guides/reporting#supported_download_formats

What are you trying to do?

**Comment by hamdibayhan** [comment]
I forgot to give the api format and type.
API = dfp_api
version = v201711
DFP API is suppoting the CSV_DUMP format, You can see:
https://developers.google.com/doubleclick-publishers/docs/reference/v201708/ReportService.ExportFormat

**Comment by mcloonan** [comment]
Oh, sorry, I didn't realize you were talking about the DFP API. I will assign it to the agent who supports DFP.

**Comment by donovanfm** [comment]
Sorry for the confusion. Our [download_report.rb](https://github.com/googleads/google-api-ads-ruby/blob/master/dfp_api/examples/v201711/report_service/download_report.rb) example could be clearer about this. The default option for report downloads is to use gzip compression. You have two options to download your report:

1) Uncompress the downloaded file (it's best to use the .gz extension in this case, e.g. 'example.csv.gz').
2) Make a call to [getReportDownloadUrlWithOptions](https://developers.google.com/doubleclick-publishers/docs/reference/v201711/ReportService#getreportdownloadurlwithoptions), where you can set [useGzipCompression](https://developers.google.com/doubleclick-publishers/docs/reference/v201711/ReportService.ReportDownloadOptions#usegzipcompression) to false.

I will make sure this example gets updated in our next release in order to make this point clear. Thanks for pointing it out!

**Comment by hamdibayhan** [comment]
You are welcome, thanks for the explanation.
