### ISSUE TITLE
API review feedback, Client#resource coding pattern

### ISSUE THREAD

**Issue by dmitchell** [googleads/google-api-ads-ruby#156]
I believe the resources should define getters and setters for all the attributes which do the appropriate wrapper calls rather than expecting the user of the api to tediously call wrapper as in the following
``` ruby
payload = client.resource(:CampaignBudget)
payload.name = client.wrapper.string(name)
```
which should just be imho
``` ruby
payload.name = name
```

Similarly, resource and operation should take hashes as args and set the corresponding attributes
``` ruby
payload = client.resource(:CampaignBudget, {name: name, amount_micros: amount, delivery_method: 'ACCELERATED', explicitly_shared: true})
```
You'll note that I expect the setter for 'delivery_method' to know how to find its enum and lookup the value. (I'm writing our own shims to do this but would prefer to use yours)

**Comment by mcloonan** [comment]
Hello,

Did you mean to file this issue on this other project: https://github.com/googleads/google-ads-ruby

And yes, we are actively looking into ways to improve the experience of using this library, including automatic getters/setters that will do the wrapping for you. The current wrapper util is a stopgap measure to help out at least somewhat in the meanwhile. Without it, you'd need to instantiate protobuf objects manually each time.

I'm going to close out this issue here because it's not related to this SOAP library. Feel free to report again in the correct place, but we are looking into this either way. Thanks!

(We are open to pull requests on that library as well; if you have a specific implementation idea or shim and would be willing to share, we'd love to see what you have.)
