### ISSUE TITLE
process GoogleAdsService.Search() never ends

### ISSUE THREAD

**Issue by jairobluecaribu** [googleads/google-api-ads-ruby#178]
since a couple of days ago, this process just stay waiting for a long time without response (not throw an error ) intermittently. I don´t now whether is a problem with the API or in my local machine. what kind of data would you need in order to help me?

**Comment by mcloonan** [comment]
It sounds like this issue is meant for a separate GitHub repo for the Google Ads API: https://github.com/googleads/google-ads-ruby

This repo is for the AdWords API library.

That said, there is a known issue in that library where if your refresh token is invalid, then API calls will just hang forever. We're investigating potential fixes for that but for now please try double-checking your credentials.
