### ISSUE TITLE
BatchJobUtils changelog

### ISSUE THREAD

**Issue by kcore** [googleads/google-api-ads-ruby#80]
for adwords_api 0.17.0 BatchJobUtils had methods  generate_soap_operations() and  post_soap_operations for adding operations.
this was changed in 0.18.0 to a single method namely upload_operations. No mention whatsoever in the changelog as well. 
What is the difference between both of them? Can we expect some consistency? Is it supposed to change again?
The changelog mentions only following changes:
  - Removed deprecated API version v201502.
  - Support for streaming report requests in report_utils.
  - Require google-ads-common 0.11.1 or later from now on.

Are there any other changes we should know about before upgrading?

**Comment by mcloonan** [comment]
I apologize for this change missing the change log. I will retroactively update the change log with the next release.

The changes to BatchJobUtils were to implement incremental uploads and to give a consistent interface, since the first iteration was a little bit more difficult to understand.

There are no more changes to BatchJobUtils in progress or planned, and there likely won't be any unless the underlying API service changes. If we do have to make changes to the BatchJobUtils, we will make an effort to preserve the existing method signatures and functionality.

**Comment by kcore** [comment]
Thanks mate. Appreciate it.

On Friday 15 January 2016, mcloonan <notifications@github.com> wrote:

> Closed #80 <https://github.com/googleads/google-api-ads-ruby/issues/80>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googleads/google-api-ads-ruby/issues/80#event-516169142>
> .
>


-- 
Sent from my iPhone
